"""Agent Workforce Ontology reference runtime.

The package deliberately separates content-derived candidate retrieval from the
host-LLM staffing decision.  It is dependency-free so the same contracts can be
used by the local Core runtime and mirrored by hosted surfaces.
"""

from .compiler import compile_workforce_profile
from .execution import (
    WORKFORCE_CAPABILITY_BINDING_PLAN_DIGEST_SCHEMA,
    WORKFORCE_CAPABILITY_BINDING_PLAN_SCHEMA,
    WORKFORCE_EXECUTION_CONTEXT_DIGEST_SCHEMA,
    WORKFORCE_EXECUTION_CONTEXT_SCHEMA,
    WORKFORCE_EXECUTION_GRAPH_DIGEST_SCHEMA,
    WORKFORCE_EXECUTION_GRAPH_SCHEMA,
    WORKFORCE_EXECUTION_PLAN_SCHEMA,
    WORKFORCE_EXECUTION_RECEIPT_SCHEMA,
    WORKFORCE_PERMISSION_POLICY_DIGEST_SCHEMA,
    WORKFORCE_PERMISSION_POLICY_SCHEMA,
    WORKFORCE_RUNTIME_BUNDLE_DIGEST_SCHEMA,
    WORKFORCE_TOOL_INVENTORY_DIGEST_SCHEMA,
    WORKFORCE_TOOL_INVENTORY_SCHEMA,
    deny_all_permission_policy,
    prepare_execution_plan,
    project_execution_context,
    project_execution_graph,
    project_permission_policy,
    validate_execution_graph,
    validate_execution_receipt,
    validate_capability_binding_plan,
    validate_tool_inventory,
    validate_permission_policy,
    validate_workforce_digest_value,
    workforce_execution_context_canonical_json,
    workforce_execution_context_digest,
    workforce_capability_binding_plan_digest,
    workforce_tool_inventory_digest,
    workforce_execution_graph_canonical_json,
    workforce_execution_graph_digest,
    workforce_permission_policy_canonical_json,
    workforce_permission_policy_digest,
    workforce_runtime_bundle_canonical_json,
    workforce_runtime_bundle_digest,
)
from .governance import apply_ontology_proposal, validate_ontology_proposal
from .contracts import (
    WORKFORCE_COVERAGE_GAP_CODES,
    WORKFORCE_ONTOLOGY_SNAPSHOT_SHA256,
    WORKFORCE_ONTOLOGY_VERSION,
    canonical_digest,
    load_ontology,
    validate_candidate_set_coverage_gaps,
    validate_coverage_gap_codes,
)
from .index import WorkforceIndex
from .lifecycle import WorkforceProjection, replay_events
from .selection import validate_host_selection
from .privacy import (
    WORKFORCE_HUB_BOUNDARY_SCHEMA,
    WorkOrderHubBoundaryError,
    assert_hub_work_order_boundary,
    validate_hub_work_order_boundary,
)

__all__ = [
    "WorkforceIndex",
    "WorkforceProjection",
    "WORKFORCE_CAPABILITY_BINDING_PLAN_DIGEST_SCHEMA",
    "WORKFORCE_CAPABILITY_BINDING_PLAN_SCHEMA",
    "WORKFORCE_COVERAGE_GAP_CODES",
    "WORKFORCE_ONTOLOGY_SNAPSHOT_SHA256",
    "WORKFORCE_ONTOLOGY_VERSION",
    "WORKFORCE_EXECUTION_PLAN_SCHEMA",
    "WORKFORCE_EXECUTION_RECEIPT_SCHEMA",
    "WORKFORCE_EXECUTION_CONTEXT_SCHEMA",
    "WORKFORCE_EXECUTION_CONTEXT_DIGEST_SCHEMA",
    "WORKFORCE_EXECUTION_GRAPH_SCHEMA",
    "WORKFORCE_EXECUTION_GRAPH_DIGEST_SCHEMA",
    "WORKFORCE_PERMISSION_POLICY_SCHEMA",
    "WORKFORCE_PERMISSION_POLICY_DIGEST_SCHEMA",
    "WORKFORCE_RUNTIME_BUNDLE_DIGEST_SCHEMA",
    "WORKFORCE_TOOL_INVENTORY_DIGEST_SCHEMA",
    "WORKFORCE_TOOL_INVENTORY_SCHEMA",
    "WORKFORCE_HUB_BOUNDARY_SCHEMA",
    "WorkOrderHubBoundaryError",
    "assert_hub_work_order_boundary",
    "canonical_digest",
    "compile_workforce_profile",
    "deny_all_permission_policy",
    "prepare_execution_plan",
    "project_execution_context",
    "project_execution_graph",
    "project_permission_policy",
    "validate_execution_graph",
    "validate_execution_receipt",
    "validate_capability_binding_plan",
    "validate_candidate_set_coverage_gaps",
    "validate_coverage_gap_codes",
    "validate_tool_inventory",
    "validate_hub_work_order_boundary",
    "validate_permission_policy",
    "validate_workforce_digest_value",
    "workforce_execution_context_canonical_json",
    "workforce_execution_context_digest",
    "workforce_capability_binding_plan_digest",
    "workforce_tool_inventory_digest",
    "workforce_execution_graph_canonical_json",
    "workforce_execution_graph_digest",
    "workforce_permission_policy_canonical_json",
    "workforce_permission_policy_digest",
    "workforce_runtime_bundle_canonical_json",
    "workforce_runtime_bundle_digest",
    "apply_ontology_proposal",
    "validate_ontology_proposal",
    "load_ontology",
    "replay_events",
    "validate_host_selection",
]
