"""Agent Workforce Ontology reference runtime.

The package deliberately separates content-derived candidate retrieval from the
host-LLM staffing decision.  It is dependency-free so the same contracts can be
used by the local Core runtime and mirrored by hosted surfaces.
"""

from .compiler import compile_workforce_profile
from .execution import (
    WORKFORCE_CAPABILITY_BINDING_PLAN_DIGEST_SCHEMA,
    WORKFORCE_CAPABILITY_BINDING_PLAN_SCHEMA,
    WORKFORCE_EXECUTION_CONTEXT_DIGEST_SCHEMA,
    WORKFORCE_EXECUTION_CONTEXT_SCHEMA,
    WORKFORCE_EXECUTION_GRAPH_DIGEST_SCHEMA,
    WORKFORCE_EXECUTION_GRAPH_SCHEMA,
    WORKFORCE_EXECUTION_PLAN_SCHEMA,
    WORKFORCE_EXECUTION_RECEIPT_SCHEMA,
    WORKFORCE_PERMISSION_POLICY_DIGEST_SCHEMA,
    WORKFORCE_PERMISSION_POLICY_SCHEMA,
    WORKFORCE_RUNTIME_BUNDLE_DIGEST_SCHEMA,
    WORKFORCE_TOOL_INVENTORY_DIGEST_SCHEMA,
    WORKFORCE_TOOL_INVENTORY_SCHEMA,
    deny_all_permission_policy,
    prepare_execution_plan,
    project_execution_context,
    project_execution_graph,
    project_permission_policy,
    validate_execution_graph,
    validate_execution_receipt,
    validate_capability_binding_plan,
    validate_tool_inventory,
    validate_permission_policy,
    validate_workforce_digest_value,
    workforce_execution_context_canonical_json,
    workforce_execution_context_digest,
    workforce_capability_binding_plan_digest,
    workforce_tool_inventory_digest,
    workforce_execution_graph_canonical_json,
    workforce_execution_graph_digest,
    workforce_permission_policy_canonical_json,
    workforce_permission_policy_digest,
    workforce_runtime_bundle_canonical_json,
    workforce_runtime_bundle_digest,
)
from .governance import apply_ontology_proposal, validate_ontology_proposal
from .contracts import (
    WORKFORCE_COVERAGE_GAP_CODES,
    WORKFORCE_ONTOLOGY_SNAPSHOT_SHA256,
    WORKFORCE_ONTOLOGY_VERSION,
    WORKFORCE_ONTOLOGY_RESOURCE,
    WORKFORCE_SELECTION_SCHEMA_ID,
    WORKFORCE_SELECTION_SCHEMA_RESOURCE,
    WORKFORCE_SELECTION_SCHEMA_VERSION,
    WORKFORCE_SELECTION_REASON_CODES,
    WORKFORCE_WORK_ORDER_SCHEMA_ID,
    WORKFORCE_WORK_ORDER_SCHEMA_RESOURCE,
    WORKFORCE_WORK_ORDER_SCHEMA_VERSION,
    canonical_digest,
    iter_workforce_contract_strings,
    load_ontology,
    load_workforce_contract_schema,
    validate_candidate_set_coverage_gaps,
    validate_coverage_gap_codes,
    validate_work_order_semantics,
    validate_workforce_json_schema,
    workforce_contract_metadata,
    workforce_finite_concepts,
    workforce_ontology_catalog,
    workforce_public_slot_ids,
)
from .index import WorkforceIndex
from .lifecycle import WorkforceProjection, replay_events
from .selection import validate_host_selection
from .privacy import (
    WORKFORCE_HUB_BOUNDARY_SCHEMA,
    WORKFORCE_SELECTION_HUB_BOUNDARY_SCHEMA,
    SelectionHubBoundaryError,
    WorkOrderHubBoundaryError,
    assert_hub_selection_boundary,
    assert_hub_work_order_boundary,
    validate_hub_selection_boundary,
    validate_hub_work_order_boundary,
)
from .federation import (
    WORKFORCE_FEDERATION_RESULT_SCHEMA,
    WORKFORCE_LINEAGE_ATTESTATION_SCHEMA,
    WORKFORCE_SOURCE_FAILURE_CODES,
    WORKFORCE_SOURCE_PRECEDENCE,
    WORKFORCE_SOURCE_SCOPES,
    WorkforceFederationError,
    federate_candidate_sets,
    sources_for_scope,
    validate_federation_result,
)
from .federation_store import FederationSessionError, FederationSessionStore
from .local_registry import LocalWorkforceRegistry
from .provenance import (
    FederatedProvenanceError,
    prepare_federated_execution_plan,
    validate_federated_host_selection,
)
from .source_service import (
    WORKFORCE_SOURCE_BUNDLE_FAILURE_CODES,
    WORKFORCE_SOURCE_BUNDLE_RECEIPT_SCHEMA,
    WORKFORCE_SOURCE_BUNDLE_TOOL,
    WorkforceSourceError,
    WorkforceSourceService,
)

__all__ = [
    "WorkforceIndex",
    "WorkforceProjection",
    "WORKFORCE_CAPABILITY_BINDING_PLAN_DIGEST_SCHEMA",
    "WORKFORCE_CAPABILITY_BINDING_PLAN_SCHEMA",
    "WORKFORCE_COVERAGE_GAP_CODES",
    "WORKFORCE_ONTOLOGY_SNAPSHOT_SHA256",
    "WORKFORCE_ONTOLOGY_VERSION",
    "WORKFORCE_ONTOLOGY_RESOURCE",
    "WORKFORCE_SELECTION_SCHEMA_ID",
    "WORKFORCE_SELECTION_SCHEMA_RESOURCE",
    "WORKFORCE_SELECTION_SCHEMA_VERSION",
    "WORKFORCE_WORK_ORDER_SCHEMA_ID",
    "WORKFORCE_WORK_ORDER_SCHEMA_RESOURCE",
    "WORKFORCE_WORK_ORDER_SCHEMA_VERSION",
    "WORKFORCE_EXECUTION_PLAN_SCHEMA",
    "WORKFORCE_EXECUTION_RECEIPT_SCHEMA",
    "WORKFORCE_EXECUTION_CONTEXT_SCHEMA",
    "WORKFORCE_EXECUTION_CONTEXT_DIGEST_SCHEMA",
    "WORKFORCE_EXECUTION_GRAPH_SCHEMA",
    "WORKFORCE_EXECUTION_GRAPH_DIGEST_SCHEMA",
    "WORKFORCE_PERMISSION_POLICY_SCHEMA",
    "WORKFORCE_PERMISSION_POLICY_DIGEST_SCHEMA",
    "WORKFORCE_RUNTIME_BUNDLE_DIGEST_SCHEMA",
    "WORKFORCE_TOOL_INVENTORY_DIGEST_SCHEMA",
    "WORKFORCE_TOOL_INVENTORY_SCHEMA",
    "WORKFORCE_HUB_BOUNDARY_SCHEMA",
    "WORKFORCE_SELECTION_HUB_BOUNDARY_SCHEMA",
    "WORKFORCE_SELECTION_REASON_CODES",
    "WORKFORCE_FEDERATION_RESULT_SCHEMA",
    "WORKFORCE_LINEAGE_ATTESTATION_SCHEMA",
    "WORKFORCE_SOURCE_FAILURE_CODES",
    "WORKFORCE_SOURCE_PRECEDENCE",
    "WORKFORCE_SOURCE_SCOPES",
    "WORKFORCE_SOURCE_BUNDLE_RECEIPT_SCHEMA",
    "WORKFORCE_SOURCE_BUNDLE_FAILURE_CODES",
    "WORKFORCE_SOURCE_BUNDLE_TOOL",
    "WorkforceFederationError",
    "FederationSessionError",
    "FederationSessionStore",
    "LocalWorkforceRegistry",
    "FederatedProvenanceError",
    "WorkforceSourceError",
    "WorkforceSourceService",
    "SelectionHubBoundaryError",
    "WorkOrderHubBoundaryError",
    "assert_hub_selection_boundary",
    "assert_hub_work_order_boundary",
    "canonical_digest",
    "compile_workforce_profile",
    "federate_candidate_sets",
    "sources_for_scope",
    "validate_federation_result",
    "validate_federated_host_selection",
    "prepare_federated_execution_plan",
    "deny_all_permission_policy",
    "prepare_execution_plan",
    "project_execution_context",
    "project_execution_graph",
    "project_permission_policy",
    "validate_execution_graph",
    "validate_execution_receipt",
    "validate_capability_binding_plan",
    "validate_candidate_set_coverage_gaps",
    "validate_coverage_gap_codes",
    "validate_tool_inventory",
    "validate_hub_work_order_boundary",
    "validate_permission_policy",
    "validate_workforce_digest_value",
    "workforce_execution_context_canonical_json",
    "workforce_execution_context_digest",
    "workforce_capability_binding_plan_digest",
    "workforce_tool_inventory_digest",
    "workforce_execution_graph_canonical_json",
    "workforce_execution_graph_digest",
    "workforce_permission_policy_canonical_json",
    "workforce_permission_policy_digest",
    "workforce_runtime_bundle_canonical_json",
    "workforce_runtime_bundle_digest",
    "apply_ontology_proposal",
    "validate_ontology_proposal",
    "load_ontology",
    "load_workforce_contract_schema",
    "iter_workforce_contract_strings",
    "replay_events",
    "validate_hub_selection_boundary",
    "validate_host_selection",
    "validate_work_order_semantics",
    "validate_workforce_json_schema",
    "workforce_contract_metadata",
    "workforce_finite_concepts",
    "workforce_ontology_catalog",
    "workforce_public_slot_ids",
]
